### ISSUE TITLE
Working List upload

### ISSUE THREAD

**Issue by SPARKESYS** [baltoky/UWFFormulaSAE#1]
I have a preliminary list of items to create our first car. Being this is our first year we are more focused on making it to competition. We will encourage innovation wherever possible however our main goal is to have a running driving car.
I need push access to commit

**Comment by baltoky** [comment]
If you want to collaborate to the project, fork the project and create a new branch then send a pull commit so that I can merge the branches you are trying to commit. Make sure you fork from the current working branch (ArgoA-master currently) so that I can merge yours with that one. Every time you start working on the project, fork the current version so that there is no overlap. I also sent you a collaborate invitation.
